### ISSUE TITLE
Time sync not working depending on the Look&Feel theme of the OS.

### ISSUE THREAD

**Issue by gillesdegottex** [gillesdegottex/dfasma#413]
Has to switch to GridLayout because we never know what themes can do to the widget sizes.

(thanks to @roebel for the bug repport!)

![screen shot 2015-09-09 at 09 56 57](https://cloud.githubusercontent.com/assets/4386879/9763133/c3bcbc58-56ff-11e5-8add-b19f75da3cd5.png)
![screen shot 2015-09-09 at 01 03 31](https://cloud.githubusercontent.com/assets/4386879/9763134/c3bccee6-56ff-11e5-8e8c-a22294f51b91.png)
![screen shot 2015-09-09 at 01 03 45](https://cloud.githubusercontent.com/assets/4386879/9763132/c3ba68ae-56ff-11e5-877b-0fe556ee9635.png)

**Comment by gillesdegottex** [comment]
Grid layout way is impossible because handles are needed between views, and there is no GridSplitter.

**Comment by roebel** [comment]
This seems to have done it - zooming works perfectly now here on MacOS X.
Thanks
Axel
