### ISSUE TITLE
Compiling on CentOS 6 fails

### ISSUE THREAD

**Issue by roebel** [gillesdegottex/dfasma#418]
Hi Gilles,

after your last fix I come a bit further but now I stop here for CentOS 6.7 (bouzouki)

g++ -c -m64 -pipe -Dfile_audio_LIBSNDFILE -DFFT_FFTW3 -D__STDC_CONSTANT_MACROS -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT -fPIE -DDFASMAVERSIONGIT=v1.2.5-6-ga7b8e57 -DPREFIX=/usr/local -DSUPPORT_SDIF -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib64/qt5/mkspecs/linux-g++-64 -I. -I/net/inavouable/u.anasynth.share/share/include -Iexternal/REAPER -Iexternal/libqaudioextra/include -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o ftlabels.o src/ftlabels.cpp
g++ -c -m64 -pipe -Dfile_audio_LIBSNDFILE -DFFT_FFTW3 -D__STDC_CONSTANT_MACROS -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT -fPIE -DDFASMAVERSIONGIT=v1.2.5-6-ga7b8e57 -DPREFIX=/usr/local -DSUPPORT_SDIF -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib64/qt5/mkspecs/linux-g++-64 -I. -I/net/inavouable/u.anasynth.share/share/include -Iexternal/REAPER -Iexternal/libqaudioextra/include -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o gvwaveform.o src/gvwaveform.cpp
src/gvwaveform.cpp: In constructor 'QGVWaveform::QGVWaveform(WMainWindow*)':
src/gvwaveform.cpp:83: error: no matching function for call to 'QAEGraphicsItemGrid::QAEGraphicsItemGrid(QGVWaveform* const, const char [2], const char [1])'
external/libqaudioextra/include/qaegraphicsitemgrid.h:24: note: candidates are: QAEGraphicsItemGrid::QAEGraphicsItemGrid()
external/libqaudioextra/include/qaegraphicsitemgrid.h:12: note:                 QAEGraphicsItemGrid::QAEGraphicsItemGrid(const QAEGraphicsItemGrid&)
src/gvwaveform.cpp: In member function 'void QGVWaveform::viewSet(QRectF, bool)':
src/gvwaveform.cpp:307: error: no matching function for call to 'QAEGraphicsItemGrid::updateLines()'
external/libqaudioextra/include/qaegraphicsitemgrid.h:27: note: candidates are: void QAEGraphicsItemGrid::updateLines(const QRectF&, const QRectF&, const QTransform&)
src/gvwaveform.cpp: In member function 'virtual void QGVWaveform::mouseMoveEvent(QMouseEvent*)':
src/gvwaveform.cpp:632: error: no matching function for call to 'QAEGraphicsItemGrid::updateLines()'
external/libqaudioextra/include/qaegraphicsitemgrid.h:27: note: candidates are: void QAEGraphicsItemGrid::updateLines(const QRectF&, const QRectF&, const QTransform&)
external/libqaudioextra/include/qaesigproc.h: At global scope:
external/libqaudioextra/include/qaesigproc.h:56: warning: 'qae::log2db' defined but not used
make: *** [gvwaveform.o] Error 1

**Comment by gillesdegottex** [comment]
It seems the libqaudioextra was not pointing to the proper commit.
You might have been unluky maybe because I have to update this in two steps and you might have pulled in between.
It runs properly on bouzouki.
Could you try again ?

**Comment by roebel** [comment]
After updating again it failed on another position. So I checked out a release tag and that worked.

It seems the problem was that I used the master branch is moving and not always in consistent state.
So I got intermediate versions. I think it would be much better keeping the master branch as a release branch so the HEAD of master is always the last release a

**Comment by gillesdegottex** [comment]
Ok, good point, I'll do this.

**Comment by gillesdegottex** [comment]
done
