### ISSUE TITLE
Waveform: Don't find a means to zoom vertically to a value that is not 0

### ISSUE THREAD

**Issue by roebel** [gillesdegottex/dfasma#424]
Hi Gilles,

I wanted to inspect a small noise that was located in the top of the amplitude maximum of a periodic waveform. I tried to zoom vertically but dfasma does not seem to have a means to zoom the signal view vertically  towards other values then 0. Am I missing something?

Best
Axel

**Comment by gillesdegottex** [comment]
That's true, the zoom is horizontal only, and tick to the zero ordinate.
I'll add an option for "unsticking" the zoom from the horizontal axis.

**Comment by gillesdegottex** [comment]
Done in 31b34d9 (will be available from v1.3.0)

See context menu of Waveform: "Zoom x-axis only"
