### ISSUE TITLE
vertical slider for time wave form

### ISSUE THREAD

**Issue by roebel** [gillesdegottex/dfasma#499]
Seems not to work here on mac os at least.
If I deactivate the "zoom on x axis only" I can zoom the y axis with the mouse wheel, and move in the y direction with the move tool but I cannot select the slider. The mouse keeps staying a cross even if I place it over the slider.
Axel

**Comment by gillesdegottex** [comment]
Can reproduce it on Linux

**Comment by roebel** [comment]
This is fine now.
