### ISSUE TITLE
Zooming in x or y direction only for the spectrogram pane

### ISSUE THREAD

**Issue by roebel** [gillesdegottex/dfasma#500]
This is more a feature request. Should not be very difficult but might be quite handy.

**Comment by gillesdegottex** [comment]
Actually, do you know the matplotlib-like zoom ?
Shift + Right-click : Zoom while keeping the point under the mouse.
Then, you can zoom on the y axis by moving the mouse on the y axis only (and same for x-axis).

If this is enough for you, I'll drop this feature request, to avoid adding redundant functionalities.

**Comment by roebel** [comment]
Yes, that is fine. The main problem here is knowing all these short cuts. The current documentation for this point seems not very clear. The detail concerning moving the mouse and the direction relation is not mentioned at all. As it is described it looks more like you shift clic and then the view zooms without any movement necessary until you release the clic.

**Comment by gillesdegottex** [comment]
doc fixed in 292265f7830d5af6cfe99196e4382fea69ec5a8f
