### ISSUE TITLE
qmake5 fails on Centos6

### ISSUE THREAD

**Issue by roebel** [gillesdegottex/dfasma#507]
Hello Gilles,

on our centos 6 work stations I get the following error when running qmake-qt5

503> qmake-qt5 -makefile -cache cache.tmp "INCLUDEPATH+=/u/formes/share/include" "LIBS+=-L/u/formes/share/lib/x86_64-Linux-rh65" dfasma.pro
Project MESSAGE: CONFIG=lex yacc debug exceptions depend_includepath testcase_targets import_plugins import_qpa_plugin qt warn_on release link_prl incremental shared qpa no_mocdepend release qt_no_framework linux unix posix gcc fft_fftw3 file_audio_libsndfile file_sdif precision_double
Project MESSAGE: Git: Version: v1.3.4
Project MESSAGE: Git: Branch: HEAD
Project MESSAGE: PREFIX=/usr/local
Project MESSAGE: PREFIXSHORTCUT=/usr/local
Project MESSAGE: For Linux
Project MESSAGE: Using GCC compiler
Project MESSAGE: For 64bits
Project MESSAGE: With double precision
Project MESSAGE: Audio file reader: libsndfile
Project MESSAGE: FFT Implementation: FFTW3
Project MESSAGE: Files: SDIF support: YES
Project ERROR: Unknown module(s) in QT: multimedia

we have libQTMultimedia available for Qt5 - in fact I had compîled dfasma 1.2 on the very same machines a few weeks ago. Any idea what could go wrong here?

I have checked out tag 1.3.4

Thanks
Axel

**Comment by gillesdegottex** [comment]
The distribution of the module multimedia is a mess.
Can you try installing all of the libqt5* libqt*5 qt5* qt*5 ? It is in one of them.

**Comment by gillesdegottex** [comment]
Compiled 1.3.4 on my previous machine:
$ cd ~gilles/dfasma_from_github
$ qmake-qt5 -makefile -cache cache.tmp "INCLUDEPATH+=/u/formes/share/include" "LIBS+=-L/u/formes/share/lib/x86_64-Linux-rh65" "CONFIG+=file_sdif" dfasma.pro
$ make

The packages on the machine you used might have been updated during a night schedule ?

**Comment by roebel** [comment]
No, contrary to what I expected machines have not been installed in the same way.
The reason was in fact that the multimedia-dev package was not installed on the machine I was trying.
