### ISSUE TITLE
Easdif en tant que submodule ?

### ISSUE THREAD

**Issue by trebmuh** [gillesdegottex/dfasma#569]
Salut @gillesdegottex ,
je me demandais si easdif pouvait être intégré en submodule (comme le sont REAPER et libqaudioextra) car j'ai essayé de faire un beau paquet pour LibraZiK et la compilation dans un chroot (pbuilder) chougne qu'elle ne trouve pas easdif/easdif.h qui lui même n'est pas empaqueté dans Debian pour le moment.
C'est envisageable pour toi ?

**Comment by gillesdegottex** [comment]
Salut, oui, je pense que c'est une bonne idee.
Je voulais pas faire un clone GitHub du repo original (Sourceforge) alors que SDIF ne m'appartient pas, mais c'est vrai que ca simplifierait beaucoup le setup.

En attendant, tu peux mettre Easdif de cote dans ton paquet, mis a part a l"Ircam je crois pas que ca soit tres utilise.

**Comment by gillesdegottex** [comment]
Can now use: https://github.com/gillesdegottex/EASDIF_SDIF

**Comment by gillesdegottex** [comment]
Done @trebmuh !
EASDIF_SDIF ne se compile tjs pas exactement de la meme maniere que les autres submodules, mais la sa compilation se fait par un extra target dans le pro file. dis-moi si ça pass pas.
